# Generated by Django 4.1.3 on 2022-12-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetaD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='filename',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
